version: '2'
services:
  node_app:
    container_name: 'ravn-challenge-backend-container-paulo-rodriguez'
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - PGHOST=postgres
    command: "npm start"
  
  postgres:
    image: "postgres:14"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=book_store
    ports:
      - '5432:5432'
    volumes:
      - book-store-db:/var/lib/postgresql/data

volumes:
  book-store-db: {}

